[package]
name = "chinese_checkers"
version = "0.1.0"
authors = ["DMilan <ckq1347@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.116.0"
piston = "0.52.1"
piston2d-graphics = "0.39.0"
conrod_core = "0.71.0"