[package]
name = "chinese_checkers"
version = "0.1.0"
authors = ["DMilan <ckq1347@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
