[package]
name = "chinese_checkers"
version = "0.1.0"
authors = ["James Pedersen", "Daniel Milanovich"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# druid = {version = "0.7.0", features = ["im"]} 
druid = { git = "https://github.com/linebender/druid.git", features = ["im", "svg"]}
rand = "0.8.3"
lazy_static = "1.4.0"
tracing = "0.1.26"
once_cell = "1.8.0"