[package]
name = "chinese_checkers_client"
version = "0.1.0"
authors = ["James Pedersen", "Daniel Milanovich"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"